global:
  resolve_timeout: 5m
route:
  receiver: 'autometrics-slack-app'
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 1m # NOTE - artifically low for testing purposes
  repeat_interval: 5m # NOTE - artifically low for testing purposes
  routes:
    - receiver: 'autometrics-slack-app'
      continue: true # This ensures that the alerting continues to the next route
    - receiver: 'lau-autometrics-slack-app'

receivers:
- name: 'autometrics-slack-app'
  webhook_configs:
  - send_resolved: true
    url: 'https://autometrics-slack-app-production.up.railway.app/api/alerts'

- name: 'lau-autometrics-slack-app'
  webhook_configs:
  - send_resolved: true
    url: 'https://p01--slackbot--ydb8zv8zls59.code.run/api/alerts'
