global:
  resolve_timeout: 5m
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 1m # NOTE - artifically low for testing purposes
  repeat_interval: 5m # NOTE - artifically low for testing purposes
  receiver: 'autometrics-slack-app'

receivers:
- name: 'autometrics-slack-app'
  webhook_configs:
  - send_resolved: true
    url: 'https://autometrics-slack-app-production.up.railway.app/api/alerts'
